// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: rpc_transfer_token.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenAddress string `protobuf:"bytes,1,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	FromAddress  string `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress    string `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
}

func (x *TransferTokenRequest) Reset() {
	*x = TransferTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfer_token_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTokenRequest) ProtoMessage() {}

func (x *TransferTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfer_token_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTokenRequest.ProtoReflect.Descriptor instead.
func (*TransferTokenRequest) Descriptor() ([]byte, []int) {
	return file_rpc_transfer_token_proto_rawDescGZIP(), []int{0}
}

func (x *TransferTokenRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *TransferTokenRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *TransferTokenRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

type TransferTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *TransferTokenResponse) Reset() {
	*x = TransferTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_transfer_token_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTokenResponse) ProtoMessage() {}

func (x *TransferTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_transfer_token_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTokenResponse.ProtoReflect.Descriptor instead.
func (*TransferTokenResponse) Descriptor() ([]byte, []int) {
	return file_rpc_transfer_token_proto_rawDescGZIP(), []int{1}
}

func (x *TransferTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_rpc_transfer_token_proto protoreflect.FileDescriptor

var file_rpc_transfer_token_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0b,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x14, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x66, 0x72, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74,
	0x6f, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x6f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x38, 0x0a, 0x15, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x79, 0x64, 0x6f, 0x67, 0x64, 0x75, 0x79, 0x75, 0x73, 0x75, 0x66, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x31, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_transfer_token_proto_rawDescOnce sync.Once
	file_rpc_transfer_token_proto_rawDescData = file_rpc_transfer_token_proto_rawDesc
)

func file_rpc_transfer_token_proto_rawDescGZIP() []byte {
	file_rpc_transfer_token_proto_rawDescOnce.Do(func() {
		file_rpc_transfer_token_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_transfer_token_proto_rawDescData)
	})
	return file_rpc_transfer_token_proto_rawDescData
}

var file_rpc_transfer_token_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_transfer_token_proto_goTypes = []interface{}{
	(*TransferTokenRequest)(nil),  // 0: pb.TransferTokenRequest
	(*TransferTokenResponse)(nil), // 1: pb.TransferTokenResponse
	(*Token)(nil),                 // 2: pb.Token
}
var file_rpc_transfer_token_proto_depIdxs = []int32{
	2, // 0: pb.TransferTokenResponse.token:type_name -> pb.Token
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_transfer_token_proto_init() }
func file_rpc_transfer_token_proto_init() {
	if File_rpc_transfer_token_proto != nil {
		return
	}
	file_token_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_transfer_token_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_transfer_token_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_transfer_token_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_transfer_token_proto_goTypes,
		DependencyIndexes: file_rpc_transfer_token_proto_depIdxs,
		MessageInfos:      file_rpc_transfer_token_proto_msgTypes,
	}.Build()
	File_rpc_transfer_token_proto = out.File
	file_rpc_transfer_token_proto_rawDesc = nil
	file_rpc_transfer_token_proto_goTypes = nil
	file_rpc_transfer_token_proto_depIdxs = nil
}
